// This file has been auto-generated by `bpm`.
// It is not meant to be edited manually.
sum     = "5cefc95aa643bae1e450814bfab2f644"
edition = "2024"

modules {

  mod "data.goray.go.ast.tokens" {
    source  = "go/ast/tokens.rego"
    sum     = "bab0cb9a884ccc814ee4a926b841684b"
    require = null
  }
  mod "data.goray.go.ast.types" {
    source  = "go/ast/types.rego"
    sum     = "36494b80dd383ded9af22ed05479e809"
    require = null
  }
  mod "data.goray.go.ast.kinds" {
    source  = "go/ast/kinds.rego"
    sum     = "585f173d18d223ebd08979781793e35d"
    require = null
  }
  mod "data.goray.go.util.ast" {
    source  = "go/utils/ast.rego"
    sum     = "fa43b753a396866fea3d89f7023a8742"
    require = null
  }
}