// This file has been auto-generated by `bpm`.
// It is not meant to be edited manually.
sum     = "93b7a1520c224e68244bf5aa195e6a6a9bc99e0a0e9e655196d48fe8763aa0e2"
edition = "2024"

modules {
  mod "data.goray.go.ast.kinds" {
    source  = "go/ast/kinds.rego"
    sum     = "153a541728495af2114d8337966b9f4b8cdacc15c27a6772d0832b2f55700cd3"
    require = null
  }
  mod "data.goray.go.ast.tokens" {
    source  = "go/ast/tokens.rego"
    sum     = "3c34ad9503578178c4278c9c6daafa8c05986d3a4d525ec146d94b57af60d494"
    require = null
  }
  mod "data.goray.go.ast.types" {
    source  = "go/ast/types.rego"
    sum     = "ea6496c760bcb8bc056623f6f6e440fb227d4862dbf7a1b917c3198aeaf46144"
    require = null
  }
  mod "data.goray.go.util.ast" {
    source  = "go/utils/ast.rego"
    sum     = "4f5eb03222a32efebd0c3667a2b9585c4c9860bc2cb3d34ef6ee7dda2d6f2c9d"
    require = null
  }
}

require {
  bundle "github.com/4rchr4y/gst" direct {
    name    = "goray"
    version = "v0.0.0+20240211095635-a119b6fa54e6"
    h1      = "d96ee4281ed9c1e23a7a535a20ad0347a76e2fb278bbbf971a97965c35b17cb5"
    h2      = "731d7f54c6852b934353a5f8ec5ed4f7f957b5c9b9ecd4fa89ad563a6e0b3bf4"
  }
}